/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : AC1.c
**     Project     : USI-0106
**     Processor   : MKL04Z32VFK4
**     Component   : AnalogComp_LDD
**     Version     : Component 01.023, Driver 01.09, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-01-19, 16:49, # CodeGen: 1
**     Abstract    :
**         This component "AnalogComp_LDD" encapsulates Analog Comparator
**         peripheral supported on Freescale CPUs.
**         This component allows to select inputs to compare,
**         get the value of the comparator and specify when to generate
**         the compare event. If available for selected CPU, component
**         supports filtering and windowing functions.


**     Settings    :
**          Component name                                 : AC1
**          Analog comparator                              : CMP0
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_CMP0
**            Interrupt priority                           : medium priority
**          Positive inputs                                : 1
**            Positive input 0                             : 
**              Pin                                        : ADC0_SE0/CMP0_IN0/PTA12/IRQ_17/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0
**              Signal                                     : TCdataIn
**              Source component                           : external
**          Negative inputs                                : 1
**            Negative input 0                             : 
**              Pin                                        : DAC6b0_Output
**              Signal                                     : 
**              Source component                           : internal
**                Component                                : DA1
**          Comparator output                              : Enabled
**            Pin                                          : PTA2/CMP0_OUT/SWD_DIO
**            Signal                                       : 
**            Filter bypass                                : Disabled
**          Output filter                                  : Disabled
**          Inverted output                                : no
**          Analog comp. mode                              : rising edge
**          Power mode                                     : Power saving
**          Pass through mode                              : Disabled
**          Hysteresis                                     : 3
**          DMA                                            : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Positive input                               : Positive input 0
**            Negative input                               : Negative input 0
**            Event mask                                   : 
**              OnCompare                                  : Enabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init - LDD_TDeviceData* AC1_Init(LDD_TUserData *UserDataPtr);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file AC1.c
** @version 01.09
** @brief
**         This component "AnalogComp_LDD" encapsulates Analog Comparator
**         peripheral supported on Freescale CPUs.
**         This component allows to select inputs to compare,
**         get the value of the comparator and specify when to generate
**         the compare event. If available for selected CPU, component
**         supports filtering and windowing functions.


*/         
/*!
**  @addtogroup AC1_module AC1 module documentation
**  @{
*/         

/* MODULE AC1. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Events.h"
#include "AC1.h"

#ifdef __cplusplus
extern "C" {
#endif 

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static AC1_TDeviceData DeviceDataPtr__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static AC1_TDeviceData* INT_CMP0__DEFAULT_RTOS_ISRPARAM;

/*
** ===================================================================
**     Method      :  AC1_Init (component AnalogComp_LDD)
*/
/*!
**     @brief
**         Initializes the device according to design-time
**         configuration properties. Allocates memory for the device
**         data structure.
**         If the <Enable in init. code> is set to "yes" then the
**         device is also enabled and some time is required before
**         stabilizing of the comparator output. If the <Interrupt
**         service/event> property is enabled, it is recommended to
**         enable events after comparator output stabilizes to prevent
**         an unwanted event invocation before output stabilization.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an events or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* AC1_Init(LDD_TUserData *UserDataPtr)
{
  AC1_TDeviceData *DeviceDataPtr;      /* LDD device structure */

  /* Allocate HAL device structure */
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPtr = &DeviceDataPtr__DEFAULT_RTOS_ALLOC;
  DeviceDataPtr->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  DeviceDataPtr->EventMask = LDD_ANALOGCOMP_ON_COMPARE; /* Store mask of enabled event */
  /* SIM_SCGC4: CMP=1 */
  SIM_SCGC4 |= SIM_SCGC4_CMP_MASK;
  /* Interrupt vector(s) allocation */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_CMP0__DEFAULT_RTOS_ISRPARAM = DeviceDataPtr;
  /* Interrupt vector(s) priority setting */
  /* NVIC_IPR4: PRI_16=0x80 */
  NVIC_IPR4 = (uint32_t)((NVIC_IPR4 & (uint32_t)~(uint32_t)(
               NVIC_IP_PRI_16(0x7F)
              )) | (uint32_t)(
               NVIC_IP_PRI_16(0x80)
              ));
  /* NVIC_ISER: SETENA|=0x00010000 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x00010000);
  /* PORTA_PCR12: ISF=0,MUX=0 */
  PORTA_PCR12 &= (uint32_t)~(uint32_t)((PORT_PCR_ISF_MASK | PORT_PCR_MUX(0x07)));
  /* PORTA_PCR2: ISF=0,MUX=2 */
  PORTA_PCR2 = (uint32_t)((PORTA_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* CMP0_CR1: SE=0,WE=0,TRIGM=0,PMODE=0,INV=0,COS=0,OPE=1,EN=0 */
  CMP0_CR1 = CMP_CR1_OPE_MASK;         /* Disable comparator and sampling */
  /* CMP0_MUXCR: PSTM=0,??=0,PSEL=0,MSEL=7 */
  CMP0_MUXCR = (CMP_MUXCR_PSEL(0x00) | CMP_MUXCR_MSEL(0x07)); /* Initialize inputs */
  /* CMP0_FPR: FILT_PER=0 */
  CMP0_FPR = CMP_FPR_FILT_PER(0x00);   /* Disable filter */
  /* CMP0_CR0: ??=0,FILTER_CNT=0,??=0,??=0,HYSTCTR=0 */
  CMP0_CR0 = (CMP_CR0_FILTER_CNT(0x00) | CMP_CR0_HYSTCTR(0x00)); /* Reset filter */
  /* CMP0_FPR: FILT_PER=0 */
  CMP0_FPR = CMP_FPR_FILT_PER(0x00);   /* Set filter period */
  /* CMP0_SCR: ??=0,DMAEN=0,??=0,IER=0,IEF=0,CFR=1,CFF=1,COUT=0 */
  CMP0_SCR = (CMP_SCR_CFR_MASK | CMP_SCR_CFF_MASK); /* Set SC register and clear flags */
  /* CMP0_CR0: ??=0,FILTER_CNT=0,??=0,??=0,HYSTCTR=3 */
  CMP0_CR0 = (CMP_CR0_FILTER_CNT(0x00) | CMP_CR0_HYSTCTR(0x03));
  /* CMP0_CR1: SE=0,WE=0,TRIGM=0,PMODE=0,INV=0,COS=0,OPE=1,EN=1 */
  CMP0_CR1 = (CMP_CR1_OPE_MASK | CMP_CR1_EN_MASK);
  /* CMP0_SCR: IER=1 */
  CMP0_SCR |= CMP_SCR_IER_MASK;        /* Enable interrupts */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_AC1_ID,DeviceDataPtr);
  return ((LDD_TDeviceData*)DeviceDataPtr); /* Return pointer to the data data structure */
}

/*
** ===================================================================
**     Method      :  AC1_Interrupt (component AnalogComp_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
PE_ISR(AC1_Interrupt)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  AC1_TDeviceData* DeviceDataPtr = INT_CMP0__DEFAULT_RTOS_ISRPARAM;
  uint8_t State;

  State = CMP_PDD_GetInterruptFlags(CMP0_BASE_PTR);
  if (((DeviceDataPtr)->EventMask & LDD_ANALOGCOMP_ON_COMPARE) != 0x00U) {
    AC1_OnCompare(DeviceDataPtr->UserDataPtr); /* Call user event */
  }
  CMP_PDD_ClearInterruptFlags(CMP0_BASE_PTR,State);
}



/* END AC1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
